### ISSUE TITLE
Support for fish

### ISSUE THREAD

**Issue by tbodt** [jcsalterego/historian#3]
Fish's history includes a little more information than just the command that was executed. `~/.local/share/fish/fish_history` is a yaml file, here's a sample:

```yaml
- cmd: v /usr/local/etc/rethinkdb.conf 
  when: 1492027898
  paths:
    - /usr/local/etc/rethinkdb.conf
```

As you can see it includes the command, a timestamp, and the filepaths references by the command.
